"""add_account_money_extend

Revision ID: 09633b4cf949
Revises: 59fc25e84ae2
Create Date: 2024-07-31 09:35:34.164412

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '09633b4cf949'
down_revision = '59fc25e84ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_money_extend',
                    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', models.types.StringUUID(), nullable=False),
                    sa.Column('total_quota', sa.Numeric(precision=10, scale=7), nullable=True),
                    sa.Column('used_quota', sa.Numeric(precision=10, scale=7), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='account_money_pkey')
                    )
    with op.batch_alter_table('account_money_extend', schema=None) as batch_op:
        batch_op.create_index('idx_account_money_account_id', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_money_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_account_money_account_id')

    op.drop_table('account_money_extend')
    # ### end Alembic commands ###
