"""forwarding address extend add status

Revision ID: afc9c19af168
Revises: fbd1f511a08e
Create Date: 2024-08-30 09:35:07.561111

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'afc9c19af168'
down_revision = 'fbd1f511a08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forwarding_address_extend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), server_default=sa.text('true'), nullable=True))
        batch_op.create_index('idx_forwarding_address_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('forwarding_address_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_forwarding_address_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
