"""update_account_money_monthly_stat_quota_precision_extend

Revision ID: 871d5faaa862
Revises: cfe4907d127b
Create Date: 2024-09-02 04:40:06.938596

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '871d5faaa862'
down_revision = 'cfe4907d127b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.alter_column('total_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('used_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('account_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.alter_column('used_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('total_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)

    # ### end Alembic commands ###
