"""update_quota_precision_extend

Revision ID: cfe4907d127b
Revises: 1b804f8bbd28
Create Date: 2024-09-02 02:46:47.381181

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'cfe4907d127b'
down_revision = '1b804f8bbd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust!
    with op.batch_alter_table('account_layover_record_extend', schema=None) as batch_op:
        batch_op.alter_column('money',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)

    with op.batch_alter_table('account_money_extend', schema=None) as batch_op:
        batch_op.alter_column('total_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('used_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)

    with op.batch_alter_table('api_token_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.alter_column('accumulated_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_used_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('month_used_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_limit_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('month_limit_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('api_token_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.alter_column('month_limit_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_limit_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('month_used_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_used_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('accumulated_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)

    with op.batch_alter_table('account_money_extend', schema=None) as batch_op:
        batch_op.alter_column('used_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('total_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)

    with op.batch_alter_table('account_layover_record_extend', schema=None) as batch_op:
        batch_op.alter_column('money',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)

    # ### end Alembic commands ###
