"""drop_api_token_money_stat_column_extend

Revision ID: dd130cfd98f8
Revises: 871d5faaa862
Create Date: 2024-09-02 07:01:48.166054

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'dd130cfd98f8'
down_revision = '871d5faaa862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_token_money_extend', schema=None) as batch_op:
        batch_op.alter_column('accumulated_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('day_used_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('month_used_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('day_limit_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('month_limit_quota',
                              existing_type=sa.NUMERIC(precision=10, scale=7),
                              type_=sa.Numeric(precision=16, scale=7),
                              existing_nullable=True)

    with op.batch_alter_table('api_token_money_daily_stat_extend', schema=None) as batch_op:
        batch_op.alter_column('accumulated_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_used_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_limit_quota',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=16, scale=7),
               existing_nullable=True)
        batch_op.drop_column('month_used_quota')
        batch_op.drop_column('month_limit_quota')

    with op.batch_alter_table('api_token_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.drop_column('day_limit_quota')
        batch_op.drop_column('day_used_quota')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('api_token_money_monthly_stat_extend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_used_quota', sa.NUMERIC(precision=16, scale=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_limit_quota', sa.NUMERIC(precision=16, scale=7), autoincrement=False, nullable=True))

    with op.batch_alter_table('api_token_money_daily_stat_extend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_limit_quota', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('month_used_quota', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
        batch_op.alter_column('day_limit_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('day_used_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('accumulated_quota',
               existing_type=sa.Numeric(precision=16, scale=7),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)

    with op.batch_alter_table('api_token_money_extend', schema=None) as batch_op:
        batch_op.alter_column('month_limit_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('day_limit_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('month_used_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('day_used_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)
        batch_op.alter_column('accumulated_quota',
                              existing_type=sa.Numeric(precision=16, scale=7),
                              type_=sa.NUMERIC(precision=10, scale=7),
                              existing_nullable=True)

    # ### end Alembic commands ###
