"""add_end_user_account_joins_extend

Revision ID: a6f3333821be
Revises: 09633b4cf949
Create Date: 2024-08-03 07:24:13.552085

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'a6f3333821be'
down_revision = '09633b4cf949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_user_account_joins_extend',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('end_user_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='end_user_account_joins_pkey')
    )
    with op.batch_alter_table('end_user_account_joins_extend', schema=None) as batch_op:
        batch_op.create_index('end_user_account_joins_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('end_user_account_joins_end_user_id_app_id_idx', ['end_user_id', 'app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('end_user_account_joins_extend', schema=None) as batch_op:
        batch_op.drop_index('end_user_account_joins_end_user_id_app_id_idx')
        batch_op.drop_index('end_user_account_joins_account_id_idx')

    op.drop_table('end_user_account_joins_extend')
    # ### end Alembic commands ###
