"""add_account_layover_record_extend

Revision ID: fbd1f511a08e
Revises: 9cb135c9d1f8
Create Date: 2024-08-27 03:08:09.118504

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'fbd1f511a08e'
down_revision = '9cb135c9d1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_layover_record_extend',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('forwarding_id', models.types.StringUUID(), nullable=False),
    sa.Column('money', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_layover_record_extend_pkey')
    )
    with op.batch_alter_table('account_layover_record_extend', schema=None) as batch_op:
        batch_op.create_index('idx_account_layover_record_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_account_layover_record_forwarding_id', ['forwarding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_layover_record_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_account_layover_record_forwarding_id')
        batch_op.drop_index('idx_account_layover_record_account_id')

    op.drop_table('account_layover_record_extend')
    # ### end Alembic commands ###
