"""add_recommended_apps_category_join_extend

Revision ID: 41e6e402d572
Revises: 408176b91ad3
Create Date: 2024-07-18 06:38:49.622100

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '41e6e402d572'
down_revision = '408176b91ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_apps_category_join_extend',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('recommended_id', models.types.StringUUID(), nullable=False),
    sa.Column('category_id', models.types.StringUUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='recommended_apps_category_id_pkey')
    )
    with op.batch_alter_table('recommended_apps_category_join_extend', schema=None) as batch_op:
        batch_op.create_index('idx_recommended_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_recommended_id', ['recommended_id'], unique=False)

    op.create_table('recommended_category_extend',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('table', sa.String(length=255), nullable=False),
    sa.Column('tag_id', models.types.StringUUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_extend_id_pkey')
    )
    with op.batch_alter_table('recommended_category_extend', schema=None) as batch_op:
        batch_op.create_index('idx_extend_table', ['table'], unique=False)
        batch_op.create_index('idx_extend_tag_bind_tag_id', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('recommended_category_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_extend_tag_bind_tag_id')
        batch_op.drop_index('idx_extend_table')

    op.drop_table('recommended_category_extend')
    with op.batch_alter_table('recommended_apps_category_join_extend', schema=None) as batch_op:
        batch_op.drop_index('idx_recommended_id')
        batch_op.drop_index('idx_recommended_category_id')

    op.drop_table('recommended_apps_category_join_extend')
    # ### end Alembic commands ###
